;; -*- mode: eask; lexical-binding: t -*-

(package "org-hash"
         "1.0.0"
         "Functions for using hashing with Org-mode entries")

(website-url "https://github.com/jwiegley/org-hash")
(keywords "org-mode" "hash")

(package-file "org-hash.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")
(source "jcs-elpa")

(depends-on "emacs" "24.1")
;; (depends-on "elsa")
;; (depends-on "flymake-eask")
